name: CI - Build & Test

# Quando executar
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Cache Maven local repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('diversidade/diversidade/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Build with Maven (skip tests)
        working-directory: ./diversidade/diversidade
        run: mvn -B clean package -DskipTests

      - name: Run tests
        working-directory: ./diversidade/diversidade
        run: mvn -B test

      - name: Upload test results (JUnit) - optional
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: diversidade/diversidade/target/surefire-reports/**/*
