services:
  oracle:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-db
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=030306
      - ORACLE_DATABASE=XE
      - ORACLE_CHARACTERSET=AL32UTF8
    volumes:
      - oracle-data:/opt/oracle/oradata
    networks:
      - diversidade-network
    healthcheck:
      test: ["CMD", "bash", "-c", "echo 'SELECT 1 FROM DUAL;' | sqlplus -s system/030306@//localhost:1521/XE"]
      interval: 30s
      timeout: 20s
      retries: 10
      start_period: 120s
    restart: unless-stopped
    shm_size: '1gb'

  app:
    build: .
    container_name: diversidade-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@oracle-db:1521:XE
      - SPRING_DATASOURCE_USERNAME=rm558929
      - SPRING_DATASOURCE_PASSWORD=030306
    depends_on:
      oracle:
        condition: service_healthy
    networks:
      - diversidade-network
    restart: on-failure

volumes:
  oracle-data:

networks:
  diversidade-network:
    driver: bridge
