name: CI - Build and Test

on:
  push:
    branches: [ feature/workflow, main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Show current directory
        run: |
          echo "📂 Current path:"
          pwd
          echo "📂 Listing:"
          ls -R

      - name: Build with Maven
        working-directory: diversidade/diversidade
        run: mvn -B clean package -DskipTests
