name: CI - Build and Test

on:
  push:
    branches: [ feature/workflow, main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Verify directory structure
        run: |
          echo "📂 Current directory:"
          pwd
          echo "📂 Listing project contents:"
          ls -R

      - name: Build with Maven
        working-directory: ./diversidade   # <- O pom.xml está dentro dessa pasta
        run: mvn -B clean package -DskipTests

      - name: Build Docker image
        run: docker build -t diversidade-api:latest .

